name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: make
    - uses: actions/upload-artifact@v2
      with:
        path: build/strfetch
        name: strfetch-linux
  
  build-osx:
  
      runs-on: macOS-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: compile
        run: make
      - uses: actions/upload-artifact@v2
        with:
          path: build/strfetch
          name: strfetch-macos
