name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: make
    - name: get artifacts
      uses: actions/download-artifact@v4
      with:
        name: build/strfetch
  
  build-osx:
  
      runs-on: macOS-latest
  
      steps:
      - uses: actions/checkout@v3
      - name: compile
        run: make
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          name: build/strfetch
